Add links to learn more part 2
ember-learn/super-rentals-tutorial pull request #166
Opened 2020-10-11 14:15 UTC by AndriyTykhan

2020-10-12 14:28 UTC, ijlee2 requested changes
Hi, @AndriyTykhan. Thank you for taking an interest in helping out with the Super Rentals tutorial!

I noticed in `04-component-basics` that the links are formatted incorrectly. As a result, I think the CI's build checks are failing.

Will you review the 3 files that you've edited and check that the links are formatted according to the description in the [issue](https://github.com/ember-learn/super-rentals-tutorial/issues/161#issue-718487975)?

To see examples of how to replace a placeholder link, I recommend looking at https://github.com/ember-learn/super-rentals-tutorial/pull/165/files

If you have questions, please feel free to comment in this pull request or in the issue. Thanks again!

2020-10-12 14:29 UTC, ijlee2 commented on src/markdown/tutorial/part-1/04-component-basics.md
> +In this chapter, you will *[refactor](https://guides.emberjs.com/release/components/introducing-components/#toc_breaking-it-into-pieces)* your existing templates to use components. We will also be ad
```suggestion
In this chapter, you will [refactor](../../../components/introducing-components/#toc_breaking-it-into-pieces) your existing templates to use components. We will also be adding a site-wide navigation bar:
```

2020-10-12 17:56 UTC, ijlee2 commented
@AndriyTykhan I made a mistake with the issue description. When adding the link, will you leave the `*` as is?

`*[description][TODO: add a link]*` becomes `*[description](link)*`

2020-10-12 17:57 UTC, ijlee2 commented on src/markdown/tutorial/part-1/04-component-basics.md
> +In a [previous chapter](../building-pages/), we got a light introduction to *[components][(https://guides.emberjs.com/release/components/introducing-components/)* when using `<LinkTo>` to connect our
```suggestion
In a [previous chapter](../building-pages/), we got a light introduction to *[components](../../../components/introducing-components/)* when using `<LinkTo>` to connect our pages. To recap, we said that components are Ember's way of creating *[custom tags][TODO: link to custom tags]* to supplement the built-in HTML tags from the browser. Now, we are going to create our own components!
```

2020-10-17 10:21 UTC, AndriyTykhan commented
@ijlee2 Hi, I've made changes that you recommend and check files, it looks good for me, but build fails and I am not sure why, could you help with it?

2020-10-17 13:48 UTC, ijlee2 commented
@AndriyTykhan Yep, I will have a look at the files. Thanks for working on the issue again!

2020-10-17 13:55 UTC, ijlee2 commented on src/markdown/tutorial/part-1/04-component-basics.md
> +When invoking a component, Ember will replace the component tag with the content found in the component's template. Just like regular HTML tags, it is common to pass *[content](https://guides.emberjs
```suggestion
When invoking a component, Ember will replace the component tag with the content found in the component's template. Just like regular HTML tags, it is common to pass *[content](../../../components/block-content/)* to components, like `<Jumbo>some content</Jumbo>`. We can enable this using the `{{yield}}` keyword, which will be replaced with the content that was passed to the component.
```

2020-10-17 14:42 UTC, ijlee2 approved these changes
Hi, @AndriyTykhan. I worked on your branch directly so that I could find and fix Markdown lint errors. It turned out there were a couple of extra characters that caused linting to fail:

- [04-component-basics, line 23 had an extra `[` character](https://github.com/ember-learn/super-rentals-tutorial/pull/166/commits/1724f67b0565ff30fadf254cd35fcb6642a36649#diff-cfd7e794f31fbc0e09db790f6d0d7df296363de1721179cbf2807179b44d576bL23)
- [06-interactive-components, line 284 had an extra `\` character](https://github.com/ember-learn/super-rentals-tutorial/pull/166/commits/11dd90dfc61c01ca755611427d7c9baf1956857b#diff-96fd485ed873422b1a6c86cc7381dcf3a7b28f788f57e8a9d5bc05ef05009b2fL284)

I also updated your branch so that all links to `guides.emberjs.com` have a relative path. Your pull request can now be merged.

Thanks again for working with me in figuring out the problem. Congratulations on making your 1st contribution to the Super Rentals tutorial! 🎉

2020-10-17 14:43 UTC, merged