Update 07-reusable-components.md
ember-learn/super-rentals-tutorial pull request #215
Opened 2022-10-11 19:34 UTC by jmpress

2022-10-12 07:29 UTC, MinThaMie requested changes
Thanks for fixing this yourself :)
The linter feels that `signup` should be `sign up`.

2022-10-12 07:29 UTC, MinThaMie commented on src/markdown/tutorial/part-1/07-reusable-components.md
> +We will use the [Mapbox](https://www.mapbox.com) API to generate maps for our rental properties. You can [sign up](https://www.mapbox.com/signup/) for free. The signup process does require a credit c
```suggestion
We will use the [Mapbox](https://www.mapbox.com) API to generate maps for our rental properties. You can [sign up](https://www.mapbox.com/signup/) for free. The sign up process does require a credit card, but the expected usage for this project should be well under the threshold for any charges to be incurred.
```

2022-10-13 06:40 UTC, MinThaMie commented
@chriskrycho the typescript part of the release goes wrong. It does not seem related to this PR at all, do you know what's up?

2022-10-25 06:27 UTC, chancancode commented
See #217. This doesn't seem to always happen – as of today I was still able to sign up for a new account, and other than verifying the email address I wasn't asked to put in my credit card. We may also want to point out that the readers can proceed without a valid token if they don't feel like signing up. How about – 

1. ~~`You can [sign up](https://www.mapbox.com/signup/) for free and without a credit card.`~~ -> `You can [sign up here](https://www.mapbox.com/signup/).`

2. Add a Zoey says... to the effect of...
   
   > The sign up process sometimes require a credit card, but the usage for this project is expected to be well within the free tire. Alternatively, you can skip this step and use a placeholder token in the subsequent step (such as `"invalid-token"`). If you choose to do this, the maps will not render and you will see "broken image" icons in their place, but the tests will pass, allowing you to still follow the rest of the tutorial.

How does that sound?

2022-10-25 06:42 UTC, chancancode commented
@MinThaMie the typescript stuff does matter – the code for building the tutorial is written in typescript and so that part of the CI pipeline is to compile them into JS (stripping the types) so node can run them.

Looking at the logs:

* last "successful" build: https://github.com/ember-learn/super-rentals-tutorial/actions/runs/3042014396
* first failing build: https://github.com/ember-learn/super-rentals-tutorial/actions/runs/3049790487/jobs/4916210279

(The "successful" build was failing for a different reason – an ember data deprecation, there were some discussions about this in the meta channel a while back)

It seems like, we have an indirect dependency on `@types/express-serve-static-core` and somehow its `index.d.ts` is tripping up the compiler with syntax errors. We are on a [fairly old typescript version](https://github.com/ember-learn/super-rentals-tutorial/blob/main/package.json#L51) so perhaps that is not super surprising, but then we are also using yarn with a lockfile, so I am not sure why that would suddenly fail.

So we will have to either troubleshoot what's going on in the CI server or upgrade TS + some of the deps? Perhaps that's something @chriskrycho can help with indeed (or at least knows someone who could). The code is [here](https://github.com/ember-learn/super-rentals-tutorial/tree/main/src/lib) and it's around a few hundred lines of vanilla typescript, so it probably won't be so bad?

2026-05-13 15:56 UTC, closed without merging

2026-05-13 15:56 UTC, kategengler commented
The tutorial no longer uses mapbox.